sudo: false
language: node_js
node_js:
  - "4"
  - "5"
  - "6"
  - "7"
  - "8"
  - "9"
matrix:
  include:
    - node_js: "10"
      env: "NVM_NODEJS_ORG_MIRROR=https://nodejs.org/download/nightly"
  allow_failures:
    - env: "NVM_NODEJS_ORG_MIRROR=https://nodejs.org/download/nightly"
os:
  - linux
  - osx
cache:
  directories:
    - node_modules
before_install:
  - "test ! -d node_modules || npm prune"
  - "test ! -d node_modules || npm rebuild"
script: "npm run-script test-cov"
after_script: "npm i coveralls@~3 && cat ./coverage/lcov.info | coveralls"
notifications:
  email:
    on_success: never
